#!/usr/bin/env python3
"""Re-open the source of every fact in facts.csv and check that its quoted passage is there.

Uses the page reader and normalisation of the register of disputed areas (data/disputed-areas/verify_quotes.py).
Writes VERIFICATION.md. Run from the repository root: python3 data/entry-rules/verify_facts.py
"""
from __future__ import annotations

import csv
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(ROOT.parent / "disputed-areas"))
from verify_quotes import page_text, squash  # noqa: E402


def main() -> int:
    with (ROOT / "facts.csv").open(newline="", encoding="utf-8") as handle:
        facts = list(csv.DictReader(handle))
    found, missing, unchecked = 0, [], []
    for f in facts:
        text = page_text(f["source_url"])
        if text is None:
            unchecked.append(f)
        elif squash(f["quote"]) in squash(text):
            found += 1
        else:
            missing.append(f)
    lines = ["# Verification of quoted passages", "", "Generated by `verify_facts.py`; do not edit.", "",
             f"Facts: {len(facts)}. Passage found in its source: {found}. Passage not found: {len(missing)}. "
             f"Source could not be read: {len(unchecked)}.", "", "## Passage not found on the page", ""]
    lines += [f"- {f['id']} / {f['field']} ({f['source_url']})" for f in missing]
    lines += ["", "## Source could not be read (check by hand)", ""]
    lines += [f"- {f['id']} / {f['field']} ({f['source_url']})" for f in unchecked]
    (ROOT / "VERIFICATION.md").write_text("\n".join(lines).rstrip("\n") + "\n", encoding="utf-8")
    print(f"{found} found, {len(missing)} not found, {len(unchecked)} unchecked")
    return 1 if missing else 0


if __name__ == "__main__":
    raise SystemExit(main())
