#!/usr/bin/env python3
"""Re-open the source of every manual fact and check that its quoted passage is on the page.

Writes VERIFICATION.md. Exit code 1 if any passage is missing from a page that could be read.
A page that cannot be fetched is reported as unchecked, not as a failure.

    python3 data/disputed-areas/verify_quotes.py
"""
from __future__ import annotations

import csv
import html
import json
import re
import sys
import time
import unicodedata
import urllib.parse
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent
CACHE = ROOT / "cache" / "pages"
AGENT = "ctr-disputed-areas/0.1 (https://github.com/uncovering-world/travel-regions-extraction)"


def squash(text: str) -> str:
    text = unicodedata.normalize("NFKC", html.unescape(text))
    text = text.translate(str.maketrans({"’": "'", "‘": "'", "“": '"', "”": '"', "–": "-", "—": "-", " ": " "}))
    text = re.sub(r"\[\d+\]|\[citation needed\]", "", text)
    return re.sub(r"\s+", " ", text).strip().lower()


def page_text(url: str) -> str | None:
    CACHE.mkdir(parents=True, exist_ok=True)
    cached = CACHE / (re.sub(r"[^A-Za-z0-9]+", "_", url)[:150] + ".txt")
    if cached.exists():
        return cached.read_text()
    try:
        match = re.search(r"//([a-z-]+)\.wikipedia\.org/.*[?&]oldid=(\d+)", url)
        if match:
            api = f"https://{match.group(1)}.wikipedia.org/w/api.php?" + urllib.parse.urlencode(
                {"action": "parse", "oldid": match.group(2), "prop": "text", "format": "json", "formatversion": 2})
            with urllib.request.urlopen(urllib.request.Request(api, headers={"User-Agent": AGENT}), timeout=30) as response:
                raw = json.load(response)["parse"]["text"]
            time.sleep(0.5)
        else:
            with urllib.request.urlopen(urllib.request.Request(url, headers={"User-Agent": AGENT}), timeout=30) as response:
                raw = response.read().decode("utf-8", "replace")
    except Exception:  # noqa: BLE001 - any failure to read means "unchecked"
        return None
    text = re.sub(r"<(script|style)[^>]*>.*?</\1>", " ", raw, flags=re.S)
    text = re.sub(r"<[^>]+>", " ", text)
    cached.write_text(text)
    return text


def main() -> int:
    with (ROOT / "sources.csv").open(newline="") as handle:
        url = {r["source_id"]: r["url"] for r in csv.DictReader(handle)}
    with (ROOT / "facts.csv").open(newline="") as handle:
        facts = [f for f in csv.DictReader(handle) if f["origin"] == "manual"]
    found, missing, unchecked = 0, [], []
    for f in facts:
        texts = [page_text(url[s]) for s in f["source_ids"].split()]
        readable = [squash(t) for t in texts if t is not None]
        if not readable:
            unchecked.append(f)
        elif any(squash(f["quote"]) in t for t in readable):
            found += 1
        else:
            missing.append(f)
    lines = ["# Verification of quoted passages", "", "Generated by `verify_quotes.py`; do not edit.", "",
             f"Manual facts: {len(facts)}. Passage found in its source: {found}. Passage not found: {len(missing)}. "
             f"Source could not be read: {len(unchecked)}.", "", "## Passage not found on the page", ""]
    lines += [f"- {f['area_id']} / {f['field']} ({f['source_ids']})" for f in missing]
    lines += ["", "## Source could not be read (check by hand)", ""]
    lines += [f"- {f['area_id']} / {f['field']} ({f['source_ids']})" for f in unchecked]
    (ROOT / "VERIFICATION.md").write_text("\n".join(lines) + "\n")
    print(f"{found} found, {len(missing)} not found, {len(unchecked)} unchecked")
    return 1 if missing else 0


if __name__ == "__main__":
    raise SystemExit(main())
